Dockerized environment
lemonatio/proof-of-liabilities pull request #1
Opened 2023-02-04 15:26 UTC by julpar

Durante la ejecución del script, descubrí que no tenía la versión correcta de Python en mi entorno. Considero que este problema puede ser común entre los usuarios de Lemon. Por lo tanto, propongo crear un script runner utilizando Docker para encapsular las dependencias. 

Esto también permitiría la posibilidad de dockerizar completamente el codebase en una sola imagen con un pipeline de construcción abierto y con la capacidad de rastreo y auditoría. Además, mantendrá las mismas características prácticas para su ejecución en entornos sin dependencias o en la nube para automatizar estas tareas.

Example run:
![image](https://user-images.githubusercontent.com/1923322/216775379-404bd16d-9591-4ff3-aa10-76598438dfc0.png)

2023-02-06 12:43 UTC, xetorthio requested changes
Muchas gracias por esto! Me parece super útil!

2023-02-06 12:43 UTC, xetorthio commented on README.md
> +./veryfy.sh -i proof.csv -r root.json
Hay un typo acá. Debería ser `verify` en lugar de `veryfy`

2023-02-06 12:43 UTC, xetorthio commented on verify.sh
> +docker run --rm -v $(pwd):/data -w /data python:3.9 python3 verify.py $@
Es mejor usar `python:3.9-slim` que es como 10x más chica y por lo tanto más rápido el download.

2023-02-06 15:59 UTC, sgalinanes requested changes
Gracias por la contribución!
Dejo un par de sugerencias con respecto al README.

2023-02-06 15:59 UTC, sgalinanes commented on README.md
> +Alternatively, if you don’t have python installed, you can use the dockerized version of the script.
```suggestion
Alternatively, if you don't have python installed, for the `verify.py` script you can use the dockerized version.
```

2023-02-06 15:59 UTC, sgalinanes commented on README.md
> +In case python dependencies are not installed a dockerized version of the script with the official python images can be used:
```suggestion
In case python dependencies are not installed, a dockerized version of the script with the official python images can be used:
```

2023-02-06 20:07 UTC, julpar commented on README.md
> +./veryfy.sh -i proof.csv -r root.json
Cambiado, gracias!

2023-02-06 20:10 UTC, julpar commented on verify.sh
> +docker run --rm -v $(pwd):/data -w /data python:3.9 python3 verify.py $@
Cambiado y probado :heavy_check_mark: ... Gracias!

2023-02-06 20:11 UTC, julpar commented
Listos los cambios @sgalinanes  :+1:

2023-02-07 13:39 UTC, sgalinanes approved these changes

2023-02-07 14:26 UTC, xetorthio approved these changes

2023-02-07 14:30 UTC, julpar commented
No conozco los guidelines para realizar el merge, pero si necesitan algo más de mi lado me avisan :metal:

2023-02-07 16:09 UTC, merged